//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Machine.EquToMesBakingAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EquToMesBakingSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseApiResponseForScada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Validation))]
    public partial class EquToMesBaking : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LoginSoapHeader loginSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback CheckSFCOperationCompleted;
        
        private System.Threading.SendOrPostCallback BakingBindContainerOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoundInBakingOperationCompleted;
        
        private System.Threading.SendOrPostCallback OutBoundInBakingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBindContainerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EquToMesBaking() {
            this.Url = global::Machine.Properties.Settings.Default.Machine_EquToMesBakingAPI_EquToMesBaking;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LoginSoapHeader LoginSoapHeaderValue {
            get {
                return this.loginSoapHeaderValueField;
            }
            set {
                this.loginSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckSFCCompletedEventHandler CheckSFCCompleted;
        
        /// <remarks/>
        public event BakingBindContainerCompletedEventHandler BakingBindContainerCompleted;
        
        /// <remarks/>
        public event BoundInBakingCompletedEventHandler BoundInBakingCompleted;
        
        /// <remarks/>
        public event OutBoundInBakingCompletedEventHandler OutBoundInBakingCompleted;
        
        /// <remarks/>
        public event GetBindContainerCompletedEventHandler GetBindContainerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckSFC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseForScada CheckSFC(EquipmentBakingCheckRequest model) {
            object[] results = this.Invoke("CheckSFC", new object[] {
                        model});
            return ((ApiResponseForScada)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSFCAsync(EquipmentBakingCheckRequest model) {
            this.CheckSFCAsync(model, null);
        }
        
        /// <remarks/>
        public void CheckSFCAsync(EquipmentBakingCheckRequest model, object userState) {
            if ((this.CheckSFCOperationCompleted == null)) {
                this.CheckSFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSFCOperationCompleted);
            }
            this.InvokeAsync("CheckSFC", new object[] {
                        model}, this.CheckSFCOperationCompleted, userState);
        }
        
        private void OnCheckSFCOperationCompleted(object arg) {
            if ((this.CheckSFCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSFCCompleted(this, new CheckSFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BakingBindContainer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseForScada BakingBindContainer(BindContainer model) {
            object[] results = this.Invoke("BakingBindContainer", new object[] {
                        model});
            return ((ApiResponseForScada)(results[0]));
        }
        
        /// <remarks/>
        public void BakingBindContainerAsync(BindContainer model) {
            this.BakingBindContainerAsync(model, null);
        }
        
        /// <remarks/>
        public void BakingBindContainerAsync(BindContainer model, object userState) {
            if ((this.BakingBindContainerOperationCompleted == null)) {
                this.BakingBindContainerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBakingBindContainerOperationCompleted);
            }
            this.InvokeAsync("BakingBindContainer", new object[] {
                        model}, this.BakingBindContainerOperationCompleted, userState);
        }
        
        private void OnBakingBindContainerOperationCompleted(object arg) {
            if ((this.BakingBindContainerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BakingBindContainerCompleted(this, new BakingBindContainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoundInBaking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseForScada BoundInBaking(EquipmentBoundInBakingRequest model) {
            object[] results = this.Invoke("BoundInBaking", new object[] {
                        model});
            return ((ApiResponseForScada)(results[0]));
        }
        
        /// <remarks/>
        public void BoundInBakingAsync(EquipmentBoundInBakingRequest model) {
            this.BoundInBakingAsync(model, null);
        }
        
        /// <remarks/>
        public void BoundInBakingAsync(EquipmentBoundInBakingRequest model, object userState) {
            if ((this.BoundInBakingOperationCompleted == null)) {
                this.BoundInBakingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoundInBakingOperationCompleted);
            }
            this.InvokeAsync("BoundInBaking", new object[] {
                        model}, this.BoundInBakingOperationCompleted, userState);
        }
        
        private void OnBoundInBakingOperationCompleted(object arg) {
            if ((this.BoundInBakingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoundInBakingCompleted(this, new BoundInBakingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OutBoundInBaking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseForScada OutBoundInBaking(EquipmentOutBoundInBakingRequest model) {
            object[] results = this.Invoke("OutBoundInBaking", new object[] {
                        model});
            return ((ApiResponseForScada)(results[0]));
        }
        
        /// <remarks/>
        public void OutBoundInBakingAsync(EquipmentOutBoundInBakingRequest model) {
            this.OutBoundInBakingAsync(model, null);
        }
        
        /// <remarks/>
        public void OutBoundInBakingAsync(EquipmentOutBoundInBakingRequest model, object userState) {
            if ((this.OutBoundInBakingOperationCompleted == null)) {
                this.OutBoundInBakingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOutBoundInBakingOperationCompleted);
            }
            this.InvokeAsync("OutBoundInBaking", new object[] {
                        model}, this.OutBoundInBakingOperationCompleted, userState);
        }
        
        private void OnOutBoundInBakingOperationCompleted(object arg) {
            if ((this.OutBoundInBakingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OutBoundInBakingCompleted(this, new OutBoundInBakingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBindContainer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseContainerInfoForScada GetBindContainer(EquipmentBakingGetBindContainerRequest model) {
            object[] results = this.Invoke("GetBindContainer", new object[] {
                        model});
            return ((ApiResponseContainerInfoForScada)(results[0]));
        }
        
        /// <remarks/>
        public void GetBindContainerAsync(EquipmentBakingGetBindContainerRequest model) {
            this.GetBindContainerAsync(model, null);
        }
        
        /// <remarks/>
        public void GetBindContainerAsync(EquipmentBakingGetBindContainerRequest model, object userState) {
            if ((this.GetBindContainerOperationCompleted == null)) {
                this.GetBindContainerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBindContainerOperationCompleted);
            }
            this.InvokeAsync("GetBindContainer", new object[] {
                        model}, this.GetBindContainerOperationCompleted, userState);
        }
        
        private void OnGetBindContainerOperationCompleted(object arg) {
            if ((this.GetBindContainerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBindContainerCompleted(this, new GetBindContainerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class LoginSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string equUserIDField;
        
        private string equPasswordField;
        
        private string operatorUserIDField;
        
        private string operatorPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string EquUserID {
            get {
                return this.equUserIDField;
            }
            set {
                this.equUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string EquPassword {
            get {
                return this.equPasswordField;
            }
            set {
                this.equPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorUserID {
            get {
                return this.operatorUserIDField;
            }
            set {
                this.operatorUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorPassword {
            get {
                return this.operatorPasswordField;
            }
            set {
                this.operatorPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BakingBindContainerSFC {
        
        private string sFCField;
        
        private string locationField;
        
        /// <remarks/>
        public string SFC {
            get {
                return this.sFCField;
            }
            set {
                this.sFCField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiResponseContainerInfoForScada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiResponseForScada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseApiResponseForScada {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiResponseContainerInfoForScada : BaseApiResponseForScada {
        
        private string containerCodeField;
        
        private BakingBindContainerSFC[] containerInfoField;
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
        
        /// <remarks/>
        public BakingBindContainerSFC[] ContainerInfo {
            get {
                return this.containerInfoField;
            }
            set {
                this.containerInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiResponseForScada : BaseApiResponseForScada {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductNG {
        
        private string nGCodeField;
        
        /// <remarks/>
        public string NGCode {
            get {
                return this.nGCodeField;
            }
            set {
                this.nGCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParamDTO {
        
        private string paramCodeField;
        
        private string paramValueField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string ParamCode {
            get {
                return this.paramCodeField;
            }
            set {
                this.paramCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ParamValue {
            get {
                return this.paramValueField;
            }
            set {
                this.paramValueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContainerResultInfo {
        
        private string sFCField;
        
        private int sFCLocationField;
        
        private System.Nullable<int> passedField;
        
        private ParamDTO[] paramListField;
        
        private ProductNG[] ngField;
        
        /// <remarks/>
        public string SFC {
            get {
                return this.sFCField;
            }
            set {
                this.sFCField = value;
            }
        }
        
        /// <remarks/>
        public int SFCLocation {
            get {
                return this.sFCLocationField;
            }
            set {
                this.sFCLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Passed {
            get {
                return this.passedField;
            }
            set {
                this.passedField = value;
            }
        }
        
        /// <remarks/>
        public ParamDTO[] ParamList {
            get {
                return this.paramListField;
            }
            set {
                this.paramListField = value;
            }
        }
        
        /// <remarks/>
        public ProductNG[] NG {
            get {
                return this.ngField;
            }
            set {
                this.ngField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OutBoundContainerInfo {
        
        private string containerCodeField;
        
        private ContainerResultInfo[] containerInfoField;
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
        
        /// <remarks/>
        public ContainerResultInfo[] ContainerInfo {
            get {
                return this.containerInfoField;
            }
            set {
                this.containerInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContainerInfo {
        
        private string sFCField;
        
        private string locationField;
        
        /// <remarks/>
        public string SFC {
            get {
                return this.sFCField;
            }
            set {
                this.sFCField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BindContainerSFC {
        
        private int countField;
        
        private string sFCField;
        
        private string locationField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string SFC {
            get {
                return this.sFCField;
            }
            set {
                this.sFCField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseApiRequestByScada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBakingGetBindContainerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentOutBoundInBakingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBoundInBakingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BindContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBakingCheckRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Validation {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBakingGetBindContainerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentOutBoundInBakingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBoundInBakingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BindContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EquipmentBakingCheckRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseApiRequestByScada : Validation {
        
        private string resourceCodeField;
        
        private string equipmentCodeField;
        
        private System.DateTime localTimeField;
        
        /// <remarks/>
        public string ResourceCode {
            get {
                return this.resourceCodeField;
            }
            set {
                this.resourceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentCode {
            get {
                return this.equipmentCodeField;
            }
            set {
                this.equipmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LocalTime {
            get {
                return this.localTimeField;
            }
            set {
                this.localTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentBakingGetBindContainerRequest : BaseApiRequestByScada {
        
        private string containerCodeField;
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentOutBoundInBakingRequest : BaseApiRequestByScada {
        
        private OutBoundContainerInfo[] outBoundContainerInfoField;
        
        /// <remarks/>
        public OutBoundContainerInfo[] OutBoundContainerInfo {
            get {
                return this.outBoundContainerInfoField;
            }
            set {
                this.outBoundContainerInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentBoundInBakingRequest : BaseApiRequestByScada {
        
        private ContainerInfo[] containerInfoField;
        
        private string containerCodeField;
        
        /// <remarks/>
        public ContainerInfo[] ContainerInfo {
            get {
                return this.containerInfoField;
            }
            set {
                this.containerInfoField = value;
            }
        }
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BindContainer : BaseApiRequestByScada {
        
        private string containerCodeField;
        
        private BindContainerSFC[] containerSFCsField;
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
        
        /// <remarks/>
        public BindContainerSFC[] ContainerSFCs {
            get {
                return this.containerSFCsField;
            }
            set {
                this.containerSFCsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EquipmentBakingCheckRequest : BaseApiRequestByScada {
        
        private string sFCField;
        
        /// <remarks/>
        public string SFC {
            get {
                return this.sFCField;
            }
            set {
                this.sFCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckSFCCompletedEventHandler(object sender, CheckSFCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseForScada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BakingBindContainerCompletedEventHandler(object sender, BakingBindContainerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BakingBindContainerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BakingBindContainerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseForScada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BoundInBakingCompletedEventHandler(object sender, BoundInBakingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoundInBakingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoundInBakingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseForScada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OutBoundInBakingCompletedEventHandler(object sender, OutBoundInBakingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OutBoundInBakingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OutBoundInBakingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseForScada)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetBindContainerCompletedEventHandler(object sender, GetBindContainerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBindContainerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBindContainerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseContainerInfoForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseContainerInfoForScada)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591