//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesOperatorLogin.asmx")]
        public string Machine_EquToMesOperatorLoginAPI_EquToMesOperatorLogin {
            get {
                return ((string)(this["Machine_EquToMesOperatorLoginAPI_EquToMesOperatorLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesHeartbeat.asmx")]
        public string Machine_EquToMesHeartbeatAPI_EquToMesHeartbeat {
            get {
                return ((string)(this["Machine_EquToMesHeartbeatAPI_EquToMesHeartbeat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesState.asmx")]
        public string Machine_EquToMesStateAPI_EquToMesState {
            get {
                return ((string)(this["Machine_EquToMesStateAPI_EquToMesState"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesAlarm.asmx")]
        public string Machine_EquToMesAlarmAPI_EquToMesAlarm {
            get {
                return ((string)(this["Machine_EquToMesAlarmAPI_EquToMesAlarm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesDownReason.asmx")]
        public string Machine_EquToMesDownReasonAPI_EquToMesDownReason {
            get {
                return ((string)(this["Machine_EquToMesDownReasonAPI_EquToMesDownReason"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesRecipeListGet.asmx")]
        public string Machine_EquToMesRecipeListGetAPI_EquToMesRecipeListGet {
            get {
                return ((string)(this["Machine_EquToMesRecipeListGetAPI_EquToMesRecipeListGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesRecipeGet.asmx")]
        public string Machine_EquToMesRecipeGetAPI_EquToMesRecipeGet {
            get {
                return ((string)(this["Machine_EquToMesRecipeGetAPI_EquToMesRecipeGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesRecipeVersionExamine.asmx")]
        public string Machine_EquToMesRecipeVEAPI_EquToMesRecipeVersionExamine {
            get {
                return ((string)(this["Machine_EquToMesRecipeVEAPI_EquToMesRecipeVersionExamine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesRecipe.asmx")]
        public string Machine_EquToMesRecipeAPI_EquToMesRecipe {
            get {
                return ((string)(this["Machine_EquToMesRecipeAPI_EquToMesRecipe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EqutoMes/EquToMesBaking.asmx")]
        public string Machine_EquToMesBakingAPI_EquToMesBaking {
            get {
                return ((string)(this["Machine_EquToMesBakingAPI_EquToMesBaking"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.36.23.222:8095/EquToMes/EquToMesUnBindContainerInCP.asmx")]
        public string Machine_UnBindContainerInCPAPI_EquToMesUnBindContainerInCP {
            get {
                return ((string)(this["Machine_UnBindContainerInCPAPI_EquToMesUnBindContainerInCP"]));
            }
        }
    }
}
