//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Machine.EquToMesUnBindContainerAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EquToMesUnBindContainerInCPSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseApiResponseForScada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Validation))]
    public partial class EquToMesUnBindContainerInCP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LoginSoapHeader loginSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback UnBindContainerInCPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EquToMesUnBindContainerInCP() {
            this.Url = global::Machine.Properties.Settings.Default.Machine_UnBindContainerInCPAPI_EquToMesUnBindContainerInCP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LoginSoapHeader LoginSoapHeaderValue {
            get {
                return this.loginSoapHeaderValueField;
            }
            set {
                this.loginSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UnBindContainerInCPCompletedEventHandler UnBindContainerInCPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LoginSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnBindContainerInCP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponseForScada UnBindContainerInCP(UnBindContainerInCP model) {
            object[] results = this.Invoke("UnBindContainerInCP", new object[] {
                        model});
            return ((ApiResponseForScada)(results[0]));
        }
        
        /// <remarks/>
        public void UnBindContainerInCPAsync(UnBindContainerInCP model) {
            this.UnBindContainerInCPAsync(model, null);
        }
        
        /// <remarks/>
        public void UnBindContainerInCPAsync(UnBindContainerInCP model, object userState) {
            if ((this.UnBindContainerInCPOperationCompleted == null)) {
                this.UnBindContainerInCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnBindContainerInCPOperationCompleted);
            }
            this.InvokeAsync("UnBindContainerInCP", new object[] {
                        model}, this.UnBindContainerInCPOperationCompleted, userState);
        }
        
        private void OnUnBindContainerInCPOperationCompleted(object arg) {
            if ((this.UnBindContainerInCPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnBindContainerInCPCompleted(this, new UnBindContainerInCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class LoginSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string equUserIDField;
        
        private string equPasswordField;
        
        private string operatorUserIDField;
        
        private string operatorPasswordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string EquUserID {
            get {
                return this.equUserIDField;
            }
            set {
                this.equUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string EquPassword {
            get {
                return this.equPasswordField;
            }
            set {
                this.equPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorUserID {
            get {
                return this.operatorUserIDField;
            }
            set {
                this.operatorUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorPassword {
            get {
                return this.operatorPasswordField;
            }
            set {
                this.operatorPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiResponseForScada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseApiResponseForScada {
        
        private int codeField;
        
        private string msgField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiResponseForScada : BaseApiResponseForScada {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseApiRequestByScada))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnBindContainerInCP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Validation {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnBindContainerInCP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseApiRequestByScada : Validation {
        
        private string resourceCodeField;
        
        private string equipmentCodeField;
        
        private System.DateTime localTimeField;
        
        /// <remarks/>
        public string ResourceCode {
            get {
                return this.resourceCodeField;
            }
            set {
                this.resourceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EquipmentCode {
            get {
                return this.equipmentCodeField;
            }
            set {
                this.equipmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LocalTime {
            get {
                return this.localTimeField;
            }
            set {
                this.localTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UnBindContainerInCP : BaseApiRequestByScada {
        
        private string containerCodeField;
        
        private string[] sFCsField;
        
        /// <remarks/>
        public string ContainerCode {
            get {
                return this.containerCodeField;
            }
            set {
                this.containerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string[] SFCs {
            get {
                return this.sFCsField;
            }
            set {
                this.sFCsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UnBindContainerInCPCompletedEventHandler(object sender, UnBindContainerInCPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnBindContainerInCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnBindContainerInCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseForScada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseForScada)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591